In [196]:
import numpy as np
import import_ipynb
import sinusfitnessfunction as ff

In [ ]:
class Genetic_Algorithm:
    def __init__(
        self,
        n_genes,
        n_alleles,
        scale,
        offset,
        size_population,
        generations,
        min_fitness_value=0.0
    ):
        self.n_genes = n_genes
        self.n_alleles = n_alleles
        self.total_alleles = self.n_alleles * self.n_genes
        self.scale = scale
        self.offset = offset
        self.size_population = size_population
        self.chromosomes = []
        self.fitness = []
        self.min_fitness_value = min_fitness_value
        self.generations = generations
    
    def init_population(self):
        self.chromosomes = np.array([[1 if np.random.rand() > 0.5 else 0 for j in range(self.total_alleles)]for i in range(self.size_population) ])
        self.fitness = np.array([ff.fitness_evaluation(self.chromosomes[i], self.n_genes, self.n_alleles, self.scale, self.offset)
                        for i in range(self.size_population)])
    
    def sort_population(self):
        pass

    def random_selection(self):        
        parents_index = np.random.randint(0, self.size_population, 2)
        return parents_index
    
    def roulette_wheel_selection(self):
        i = 0
        prob_population = 1/(1 + (self.fitness) - self.min_fitness_value)
        prob_population_sum = np.sum(prob_population)
        prob_ind_i = prob_population[i]/prob_population_sum
        sum = prob_ind_i
        r = np.random.rand()
        while sum <= r:
            i += 1
            prob_ind_i = prob_population[i]/prob_population_sum
            sum += prob_ind_i
        return i
    
    def crossover(self, parent1, parent2):
        crossover_point = np.random.randint(0, self.total_alleles)
        offspring = []
        offspring.append(np.concatenate((parent1[0:crossover_point], parent2[crossover_point:])))
        offspring.append(np.concatenate((parent2[0:crossover_point], parent1[crossover_point:])))
        offspring = np.array(offspring)
        return offspring
    
    def start(self):
        self.init_population()
        generation_counter = 0
        # Sort population by fitness
        while generation_counter <= self.generations:
            id_parent1 = self.roulette_wheel_selection()
            id_parent2 = self.roulette_wheel_selection()
            offspring = self.crossover(
                self.chromosomes[id_parent1],
                self.chromosomes[id_parent2]
            )
            self.chromosomes = np.vstack((self.chromosomes, offspring))
        

In [ ]:
Genetic_Algorithm1 = Genetic_Algorithm(1, 10, 100, 0, 100, 1000)
Genetic_Algorithm1.chromosomes

[]

In [199]:
Genetic_Algorithm1.init_population()
Genetic_Algorithm1.chromosomes

[5.33]
[7.98]
[4.73]
[1.55]
[8.41]
[5.97]
[4.78]
[4.67]
[9.3]
[1.94]
[8.33]
[8.1]
[8.3]
[7.37]
[5.21]
[1.83]
[10.02]
[7.68]
[2.19]
[8.6]
[1.76]
[7.23]
[2.3]
[8.44]
[9.53]
[1.3]
[0.47]
[6.1]
[7.97]
[6.55]
[7.96]
[5.79]
[10.07]
[7.31]
[4.73]
[5.77]
[2.83]
[1.12]
[8.97]
[5.43]
[6.95]
[8.71]
[7.37]
[8.85]
[8.35]
[5.74]
[4.58]
[8.81]
[2.74]
[7.43]
[2.41]
[3.6]
[6.48]
[9.11]
[6.33]
[7.67]
[1.41]
[3.26]
[8.32]
[8.24]
[7.86]
[4.34]
[4.89]
[4.02]
[6.34]
[1.07]
[9.45]
[5.16]
[9.25]
[5.59]
[4.6]
[6.94]
[3.27]
[0.43]
[6.89]
[1.19]
[3.39]
[7.22]
[3.28]
[3.78]
[6.52]
[1.09]
[4.16]
[3.97]
[7.35]
[2.26]
[9.68]
[1.36]
[3.43]
[1.35]
[5.85]
[8.16]
[9.78]
[5.56]
[3.3]
[6.84]
[2.71]
[7.63]
[3.27]
[0.81]


array([[1, 0, 0, 0, 0, 1, 0, 1, 0, 1],
       [1, 1, 0, 0, 0, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 0, 1, 1, 0, 0, 1],
       [0, 0, 1, 0, 0, 1, 1, 0, 1, 1],
       [1, 1, 0, 1, 0, 0, 1, 0, 0, 1],
       [1, 0, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 1, 1, 0, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 0, 1, 0, 0, 1, 1],
       [1, 1, 1, 0, 1, 0, 0, 0, 1, 0],
       [0, 0, 1, 1, 0, 0, 0, 0, 1, 0],
       [1, 1, 0, 1, 0, 0, 0, 0, 0, 1],
       [1, 1, 0, 0, 1, 0, 1, 0, 1, 0],
       [1, 1, 0, 0, 1, 1, 1, 1, 1, 0],
       [1, 0, 1, 1, 1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1, 0, 0, 1],
       [0, 0, 1, 0, 1, 1, 0, 1, 1, 1],
       [1, 1, 1, 1, 1, 0, 1, 0, 1, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 1, 1, 0, 1, 1],
       [1, 1, 0, 1, 0, 1, 1, 1, 0, 0],
       [0, 0, 1, 0, 1, 1, 0, 0, 0, 0],
       [1, 0, 1, 1, 0, 1, 0, 0, 1, 1],
       [0, 0, 1, 1, 1, 0, 0, 1, 1, 0],
       [1, 1, 0, 1, 0, 0, 1, 1, 0, 0],
       [1, 1, 1, 0, 1, 1, 1, 0, 0, 1],
       [0, 0, 1, 0, 0, 0,

In [200]:
Genetic_Algorithm1.fitness

array([[1.06526421],
       [0.74207019],
       [1.24984493],
       [0.74978376],
       [0.59936338],
       [0.55809056],
       [1.24771525],
       [1.24910172],
       [0.12554558],
       [0.68261501],
       [0.63882652],
       [0.71988981],
       [0.65217183],
       [0.63514926],
       [1.12872539],
       [0.71659439],
       [0.81069262],
       [0.73490333],
       [0.56434089],
       [0.4843971 ],
       [0.73215432],
       [0.56155854],
       [0.49570521],
       [0.58314931],
       [0.35502798],
       [0.71355819],
       [0.20288629],
       [0.4321625 ],
       [0.74327742],
       [0.01366018],
       [0.74438532],
       [0.723434  ],
       [0.85137586],
       [0.60565479],
       [1.24984493],
       [0.74095472],
       [0.05657499],
       [0.65010044],
       [0.18926285],
       [1.00337884],
       [0.36848613],
       [0.40544974],
       [0.63514926],
       [0.29364844],
       [0.6294845 ],
       [0.76686544],
       [1.24124937],
       [0.326

In [207]:
id = Genetic_Algorithm1.roulette_wheel_selection()
print(id)
Genetic_Algorithm1.fitness[id]

64


array([0.19321587])