In [46]:
import numpy as np
import import_ipynb
import sinusfitnessfunction as ff

In [47]:
class Genetic_Algorithm:
    def __init__(
        self,
        n_genes,
        n_alleles,
        scale,
        offset,
        size_population,
    ):
        self.n_genes = n_genes
        self.n_alleles = n_alleles
        self.total_alleles = self.n_alleles * self.n_genes
        self.scale = scale
        self.offset = offset
        self.size_population = size_population
        self.chromosomes = []
        self.fitness = []
    
    def init_population(self):
        self.chromosomes = np.array([[1 if np.random.rand() > 0.5 else 0 for j in range(self.total_alleles)]for i in range(self.size_population) ])
        self.fitness = [ff.fitness_evaluation(self.chromosomes[i], self.n_genes, self.n_alleles, self.scale, self.offset)
                        for i in range(self.size_population)]


In [48]:
Genetic_Algorithm1 = Genetic_Algorithm(1, 11, 100, 1023, 5)
Genetic_Algorithm1.chromosomes

[]

In [49]:
Genetic_Algorithm1.init_population()
Genetic_Algorithm1.chromosomes

[2.49]
[-1.94]
[8.5]
[-8.08]
[-6.4]


array([[1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0],
       [0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1],
       [1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1],
       [0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1],
       [0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1]])

In [50]:
Genetic_Algorithm1.fitness

[array([0.35645352]),
 array([1.18261501]),
 array([0.54848711]),
 array([1.2245664]),
 array([0.3665492])]